### ISSUE TITLE
URL formatting for public info

### ISSUE THREAD

**Issue by chickdastardly** [ukrda/muster#1]
Plan for URL formats for public view of data

{baseuri}/{league-code}
*basic public information about league (name etc)*
*should this be a URL friendly league-name rather than league code? e.g bristol-roller-derby instead of brd*

{baseuri}/{league-code}/charters
*all current charters (list of links to below or full info?)*
{baseuri}/{league-code}/charters/womens
*current women's charter*
{baseuri}/{league-code}/charters/mens
*current men's charter*
{baseuri}/{league-code}/charters/coed
*current co-ed charter*

**Comment by akhumphrey** [comment]
I think this is done to our discussion points now. Closing, but reopen if I'm crazy :)
